Gui dev
brandalley-data/brandalley-dbt pull request #280
Opened 2023-05-09 15:01 UTC by gui-brandalley

2023-05-09 15:44 UTC, nicklupu requested changes

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__sla_policies_override.sql
> +select *,
can you be consistent with model naming? this is called override but in other places youve called them overwrite

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
why do you need to extract these are dbt level? cant they be at metric level in lightdash?

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +     when requester_wait_time_in_business_minutes >1 and requester_wait_time_in_business_minutes <=3 then '1-3 mins'
just fyi eg when `requester_wait_time_in_business_minutes <=3` would be the same as `when requester_wait_time_in_business_minutes >1 and requester_wait_time_in_business_minutes <=3` as anything < 1 will have already fallen into the bucket above, so in each of the cases the lower boundary isnt needed

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +if(is_one_touch_resolution, 1, 0)                                   as one_touch_tickets,
i think we should set these as booleans eg true or false rather than as int 1/0 as bigquery will see it as a int column rather than a bool column, and then naming convention of them can be is_one_touch_ticket etc

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +if(is_one_touch_resolution, 1, 0)                                   as one_touch_tickets,
have you done it this way so you can sum ticket counts? i still think it should be metric of sum(if x is true, 1,0) in the metric definition instead so can still filter this table easily on whether it is a certain ticket type etc and so the info can be stored as a bool

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +DATE_DIFF(current_timestamp, created_at, DAY)                       as ticket_age,
this can be as metric too, so that if we do want to make these tables incremental ultimately then it isnt in the underlying data and can be calculated on the fly rather than already processed in the model itself

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_call_metric.sql
> +FORMAT_DATE('%a', created_at)                                                                                           as created_at_day_of_week,
same q as to why these are extracted in dbt

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +            case when custom_contact_reason like '%order_info/issue%' then 'Order Info/Issue'
i think you could probably just do initcap(replace(custom_contact_reason, '_', ' ')) to replace all of these going forward rather than having to manually do

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_call_metric.sql
> +case when duration < 300 then '0-5 min'
same case statement point as above and bool etc

2023-05-09 15:44 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +            custom_tracking_,
should this have an underscore at the end without anything else?

2023-05-10 08:13 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
Problem is that in LD, when you use a field in a table calculation, you still need to group by this field. So here, even if we would get the extract done in LD, the grouping would be wrong as done on created_at which is a more granular level.

2023-05-10 08:24 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +if(is_one_touch_resolution, 1, 0)                                   as one_touch_tickets,
The info is already stored as a bool but I did it this way as we can't have the same metric with different filters in LD.
For example, we want a table with number of tickets, number of short resolution tickets (time_to_answer<20) and number of One-touch tickets (is_one_touch_resolution=true).
These 3 metrics are based on Ticket id, which is the first issue as we can't use multiple time the same metric in LD. Secondly we can't filter on metrics individually, filters are applied on all metrics of the report.
Finally, we have the same issue as earlier, whenever you use a dimension, the metrics and table calculations have to be grouped by this dimension too.

2023-05-10 08:34 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__sla_policies_override.sql
> +select *,
Updated

2023-05-10 08:35 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +     when requester_wait_time_in_business_minutes >1 and requester_wait_time_in_business_minutes <=3 then '1-3 mins'
Updated, I don't know why I get this habit, maybe from BI filters

2023-05-10 08:36 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +DATE_DIFF(current_timestamp, created_at, DAY)                       as ticket_age,
The "age" dimensions can be in LD indeed, updated.

2023-05-10 08:51 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +            case when custom_contact_reason like '%order_info/issue%' then 'Order Info/Issue'
There are different granular levels and this allow to extract the top ones.
custom_contact_reason can have value :
order_info/issue_cancel_order
order_info/issue_order_status
order_info/issue_product_issue
order_info/issue_shipping_issue
order_info/issue::refund_enquiry

So I couldn't think of an easier way to extract just top level information (order_info/issue) as the naming convention of the value of the field is not really logical

2023-05-10 08:52 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_call_metric.sql
> +case when duration < 300 then '0-5 min'
Updated

2023-05-10 08:54 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +            custom_tracking_,
Yes, that's how it is defined in the source zendesk table from fivetran

2023-05-10 09:38 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
so i meant rather than it needing to be in the dbt model (ie to keep that as clean as possible you would have in the .yml file as another dimension

- name: created_at
  description: "created_at"
  meta:
          dimension:
            type: timestamp
- name: created_at_day_of_week
  description: "created_at day of week"
  meta:
          dimension:
            type: number
            sql: 'FORMAT_DATE('%a', ${created_at})'

or something like that

2023-05-10 09:41 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +if(is_one_touch_resolution, 1, 0)                                   as one_touch_tickets,
not sure i follow - you would just have it in the .yml file as a metric of say count(distinct if(time_to_answer<20,ticket_id,null)) etc?

2023-05-10 09:49 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +            case when custom_contact_reason like '%order_info/issue%' then 'Order Info/Issue'
yeah potentially with a regex but if theyre not gonna change and will always be these then doesnt matter too much!

2023-05-10 09:55 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
Ok, so it is just better to put things as much as possible in the yml? It means the functions will run whenever we do the query in LD but this shouldn't be to resource intensive?

2023-05-10 10:00 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
i think in these cases yes when its just some formatting because the dbt models are running so often and its a pretty simple sql transformation to run on them at query time

2023-05-10 10:01 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
basically id say generally do it in the lightdash yml for fairly simple changes you want, but if its something more complex then do it in the dbt model, but ideally want to keep the underlying data with as least duplicated info as possible

2023-05-10 15:34 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk__ticket_metrics_overwrite.sql
> +FORMAT_DATE('%a', created_at)                                       as created_at_day_of_week,
@nicklupu Everything has been moved to the yml

2023-05-11 10:17 UTC, nicklupu approved these changes
just a couple of queries

2023-05-11 10:17 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/_docs.yml
> +              sql: if(completion_status='completed' and direction='Inbound', 1, 0)
is this status correct?

2023-05-11 10:17 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/_docs.yml
> +  - name: call_leg_overwrite
weird that zendesk call it call_leg haha

2023-05-11 13:03 UTC, merged