streamkap.sales_flat_shipment_track + zohodesk incremental
brandalley-data/brandalley-dbt pull request #303
Opened 2023-05-25 13:56 UTC by gui-brandalley

2023-05-30 15:34 UTC, nicklupu requested changes

2023-05-30 15:34 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/customers/_docs.yml
> -              label: 'Members'
can you leave this as members - as technically it is as a customer in customers table is actually a member, not necessarily a customer and thats lead to some confusion when people exploring the customers table

2023-05-30 15:34 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> -              label: 'Avg Items per Order'
same with all these i think your merge in has removed the label changes i made this morning

2023-05-30 15:34 UTC, nicklupu commented on dbt/brandalley-dbt/models/sources/streamkap_current/sales/_docs.yml
> -            sql: 'if(stg__salesrule_coupon.ba_site = "FR",datetime(stg__salesrule_coupon.expiration_at, "Europe/Paris"),datetime(stg__salesrule_coupon.expiration_at, "Europe/London"))'
these shouldnt be overwritten

2023-05-30 15:34 UTC, nicklupu commented on dbt/brandalley-dbt/models/sources/streamkap_current/sales/stg__sales_flat_shipment_track.sql
> +    datetime(cast(created_at as timestamp), "Europe/London") as created_at,
reason why ive done the casting in the lightdash yml instead is so that all the data in the wh remains consistent at UTC, and hopefully LD will implement timezones soon and we can drop all of our manual overriding and WH remains in UTC

2023-05-31 08:32 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/customers/_docs.yml
> -              label: 'Members'
Sorry, the conflict confused me and I kept the wrong one. It should be back to normal

2023-05-31 08:33 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/sources/streamkap_current/sales/stg__sales_flat_shipment_track.sql
> +    datetime(cast(created_at as timestamp), "Europe/London") as created_at,
Ok, I've moved the casting

2023-05-31 10:20 UTC, nicklupu requested changes
just a couple of the overwrite issues still too otherwise LGTM.

incremental wise just a suggestion to simplify it :)

2023-05-31 13:04 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +            sum_of_order_ids:
It's completely useless. Not sure why it was there...

2023-05-31 13:04 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +        description: "Total Invoiced Units"
Should be good now.

2023-05-31 13:58 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/refunds/_docs.yml
> +            time_intervals: ['RAW', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', 'DAY_OF_WEEK_NAME', 'MONTH_NAME', 'QUARTER_NAME']
thinking about it these could probably be a var in the dbt_project.yml file and then just use that var in each place so dont have to write them all out each time, but that can be a future improvement haha

2023-05-31 13:58 UTC, nicklupu approved these changes

2023-05-31 14:04 UTC, merged