Adding join from orderlines to stock file and new attribute for zendesk: split shipment information and dispatch/delivery date information
brandalley-data/brandalley-dbt pull request #450
Opened 2023-08-15 10:32 UTC by gui-brandalley

2023-08-15 14:27 UTC, nicklupu requested changes

2023-08-15 14:27 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/catalog/stock_file.sql
> +        date(stock_prism.delivery_date)                 as stock_delivery_date,
why this rename? it is the last stock delivery date?

2023-08-15 14:27 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +        on sfo.order_id=ship.order_id and sfo.ba_site=ship.ba_site
shipment count of order id level shouldnt be joined to order line level, its at order level, or the count needs to come from joining to shipment_item with the count additionally based on the order item id too

2023-08-15 14:27 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +        - join: stock_file
whats this join for too? this is going to cause some funky metrics from stock file too and not sure the latest stock file should be joining to historical orders?

2023-08-15 14:27 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +        left outer join {{ ref('shipping')}} s
is this 1 - 1 join? more than one shipment of a sku is going to double count qtys

2023-08-15 14:27 UTC, nicklupu commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +        where ol.ba_site='UK'
can do the join on FR now too

2023-08-15 14:50 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +        left outer join {{ ref('shipping')}} s
It is 1 - n, an orderline can get multiple shipments but we gt the max(shipment_date) for that as we want only to take in account the date of the last shipment made.

2023-08-15 14:50 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +        where ol.ba_site='UK'
Yes, updating.

2023-08-15 14:50 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/catalog/stock_file.sql
> +        date(stock_prism.delivery_date)                 as stock_delivery_date,
Made an update and rolled back and I thought it was the initial name. I'll change it back.

2023-08-15 14:50 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +        on sfo.order_id=ship.order_id and sfo.ba_site=ship.ba_site
Yes, I initially set it up there as I was not planning to use Orders in the zendesk table but I do now and it make sense to get this attribute tied to it instead of Orderlines. Updating.

2023-08-15 14:50 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +        - join: stock_file
It's for the cover report. We need to get the orders units with the stock units in the same report.

2023-08-15 14:56 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +        - join: stock_file
but what is the filter on order date for that then as theyre not comparable with a changing date range? is it over all time?

2023-08-15 15:28 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +        - join: stock_file
It's all orders since the first time they've been ordered this year. For stock file, date is not important, we just want to know the units in stock.

2023-08-16 08:27 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/customer_service/zendesk/zendesk_tickets_detailed.sql
> +        left outer join {{ ref('shipping')}} s
It's updated now

2023-08-16 10:33 UTC, nicklupu approved these changes

2023-08-16 12:44 UTC, merged