Adding logic on OrderLines to get max(number of shipment per order)
brandalley-data/brandalley-dbt pull request #489
Opened 2023-09-25 15:59 UTC by gui-brandalley

We identify shipments this way in an order this way:
- WH units are 1 "shipment"
- Each SF units from the same supplier are 1 "shipment"
- Each Csgt units from the same supplier are 1 "shipment"

So if we have:

- SKU A from WH
- SKU B from WH
- SKU C from WH
- SKU D consignment from Supplier 1
- SKU E consignment from Supplier 1
- SKU F consignment from Supplier 2
- SKU G SF from Supplier 3
- SKU H SF from Supplier 3

That means 4 shipments, for WH, Cgt_Sup_1, Cgt_Sup_2, SF_Sup3.

2023-09-25 16:42 UTC, nicklupu requested changes

2023-09-25 16:42 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +            else 'SF_' || eaov_brand.value
what happens in the cases where its partially whs and partially another method at OrderLine level?

2023-09-25 16:42 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
i dont really follow this logic.. what are you exactly trying to achieve?

2023-09-25 16:42 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +      - name: max_suppliers_nb
this name doesnt match what youre calling the column in the model above

2023-09-26 08:17 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +            else 'SF_' || eaov_brand.value
If it is WH and Csgt it will be Csgt, WH and SF it will be SF, Csgt and SF it will be SF. That's the logic here, but the correct one should be to split it in 2 lines imo. It is really impactful though as it changes the unique key from SKU + order_id to SKU + order_id + order_type (WH, Csgt or SF).

2023-09-26 08:21 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
Michael is looking for a report where we can get shipping cost divided per "shipment". I am trying to get the number of "shipment" per order so we can divide the shipping cost per it.
So, following the example described in this PR, we would get 4 different "shipments", and for a shipping cost of 6 it would 1.50 each (WH, Cgt_Sup_1, Cgt_Sup_2, SF_Sup3)

2023-09-26 08:26 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/_docs.yml
> +      - name: max_suppliers_nb
Updated. I also added the group_label

2023-09-26 10:05 UTC, nicklupu requested changes

2023-09-26 10:05 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
i also still dont really understand this count of order suppliers being relevant to this - the cte you currently have wouldnt give you 4 as the max row number as you're not partitioning by shipment type.

2023-09-26 12:25 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
I'll check to move it to orders_enriched. I never knew if this model was really used. I initially planned to add it to Orders but it is not possible as we don't get the information about supplier.
For partitioning, if I add shipment_type in the partition by, I get 1 as rn for each row. When removing it, the result seems correct with incrementing by 1 for each supplier.

2023-09-26 13:36 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
yeah, its generally used in quite a few places for stuff thats additional to the magento order level.
yeah sorry i updated to remove the partition by shipment type - in the case it appears as its correct but if you had say two items with the same supplier in an order then it would give you the incorrect number, as say five items, and two of them had the same supplier (shipment) then that cte would give you 5 rather than 4

2023-09-27 14:11 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
I don't think it would because we are not grouping by SKU/item_id so we're getting only 1 line per different shipment in the CTE, even though we could get 2+ lines for 1 shipment in the first "order_lines" CTE.

2023-09-27 14:24 UTC, nicklupu commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
hmm ok, i see what you mean but i still dont think this cte is the most efficient way of doing it then, you could just do a count(distinct shipment_type), order_id from order_lines group by 2, although not sure i agree that all wh units should be classed under 1 "shipment" if there may have been multiple from the wh.

2023-09-28 14:35 UTC, gui-brandalley commented on dbt/brandalley-dbt/models/magento/sales/orders/OrderLines.sql
> +order_suppliers as (
Indeed, it's much easier with a simple count(distinct...).
I updated it and moved it to orders_enriched.
Regarding the WH units classified as "1" shipment, that's what Michael wanted as the logic. I think it is because we consider as only 1 shipment things sent from our WH (even if it can be physically more) and then 1 shipment per supplier for Csgt and SF.

2023-09-29 12:42 UTC, nicklupu approved these changes

2023-09-29 12:43 UTC, nicklupu commented
dev db didnt clone properly last sun so can ignore the start preview error

2023-09-29 13:03 UTC, merged