Josh dev
brandalley-data/brandalley-dbt pull request #71
Opened 2023-02-07 14:06 UTC by gui-brandalley

2023-02-08 12:04 UTC, nicklupu requested changes

2023-02-08 12:04 UTC, nicklupu commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +    AND c.cohort_ts >= '2021-01-01'
i dont think we should be using this filter here if possible as it makes the whole table not very flexible, and it should be used in the join to customers_enriched directly in lightdash

2023-02-08 12:50 UTC, josh-olufemi commented on dbt/brandalley-dbt/models/Avora_models/models.yml
> +      - name: order_ts
I think that helps a lot in terms of naming conventions, the only issue is, I think we could start using them on the NEW models you and I create. Renaming columns in the models that already exist will break a lot of things, especially on LD for a reports/dashboards that executive stakeholders view. I do agree with the naming conventions you suggested. I will rename order_ts to order_at

2023-02-08 13:01 UTC, josh-olufemi commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +    AND c.cohort_ts >= '2021-01-01'
this filter, can I just remove it like you said and apply it in Lightdash? I am not sure I can add logic LIKE ` AND c.cohort_ts >= '2021-01-01'` in a table join for LD in the models.yaml file

2023-02-08 13:03 UTC, josh-olufemi commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +  FROM `datawarehouse-358408.analytics_magento.OrderLines` as o
there's a slight issue here, the ORDERS table has no customer_id, I joined the ORDERS_ENRICHED table to ORDER_LINES on the order_id column for both tables. So if we use ORDERS instead of ORDERLINES, the customer_id field will no longer be present as a column and the filter won't be present. I proposed removing the filter altogether and doing it on LD

2023-02-08 13:05 UTC, nicklupu commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +    AND c.cohort_ts >= '2021-01-01'
i didnt mean in the yml file i meant filter it in the top of the chart where you pick the filters?

2023-02-08 13:05 UTC, nicklupu commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +  FROM `datawarehouse-358408.analytics_magento.OrderLines` as o
does it not have it? looks like it has customer_id in the dbt model?

2023-02-08 13:24 UTC, josh-olufemi commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +    AND c.cohort_ts >= '2021-01-01'
Yeah, sorry about that. I am applying it in LD like I displayed on the call we had

2023-02-09 16:02 UTC, josh-olufemi commented on dbt/brandalley-dbt/models/Avora_models/orders_enriched.sql
> +  FROM `datawarehouse-358408.analytics_magento.OrderLines` as o
done

2023-02-09 17:06 UTC, nicklupu approved these changes

2023-02-09 17:07 UTC, merged